=== ccpomposo/test-tutorsexto/xml/mexico.dtd
<?xml encoding="UTF-8">
<!ELEMENT Mexico(estado)+>
<!ELEMENT estado(nombre, municipio?, localidad?)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT municipio EMPTY>
<!ELEMENT localidad EMPTY>

=== ccpomposo/test-tutorsexto/xml/mexico.xml
<?xml version="1.0"?>
<!DOCTYPE Mexico SYSTEM "mexico.dtd">
<Mexico>
    <estado>
        <nombre>Espa√±a</nombre>
        <municipio />
        <localidad />
    </estado>
    <estado>
        <nombre>Noruega</nombre>
        <localidad />
    </estado>
    <estado>
        <nombre>Austria</nombre>
        <municipio />
    </estado>
</Mexico>
